spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

--- #local 환경
spring:
  profiles:
    active: local
  jpa:
    generate-ddl: true
  datasource:
    #url: jdbc:log4jdbc:mysql://211.115.206.199:3307/sellove?serverTimezone=UTC
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #username: cardmobile
    #password: Zkemahqkdlf199@
    url: jdbc:h2:~/snsmarket
    driver-class-name: org.h2.Driver
    username: snsmarket
    password: snsmarket1234
logging:
  config: classpath:log4j2-local.xml