spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

--- #prod 환경
spring:
  profiles:
    active: prod
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 2
        max-idle: 10
        max-active: 10
  jpa:
    generate-ddl: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.115.206.199:3306/cardmobile?serverTimezone=UTC
    username: cardmobile
    password: Zkemahqkdlf199@