spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 584801572428288
            client-secret: 6f198b833ffd8499efa5d68a6e54bdb8
          facebook:
            client-id: 584801572428288
            client-secret: 6f198b833ffd8499efa5d68a6e54bdb8
custom:
  oauth2:
    kakao:
      client-id: 6f0a5e9c1f92e7d6daac97ccaa2c16f0
      client-secret: cp14AXO2zVTyTKgXu2zEnqQ4hAyCPbOS
    naver:
      client-id: G5mtIBALuMssfKHHj3b0
      client-secret: BgDF0uxPkB

--- #local 환경
spring:
  profiles:
    active: local
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:log4jdbc:mysql://211.115.206.199:3307/sellove?serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: cardmobile
    password: Zkemahqkdlf199@
server:
  port: 8994
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/snsmarket
#    username: snsmarket
#    password: snsmarket1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://211.115.206.199:3306/cardmobile?serverTimezone=UTC
#    username: cardmobile
#    password: Zkemahqkdlf199@